<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ToDo_Backend_InterfaceAdapters_Repository</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToDo-Backend-CA-AplicationLayer\ToDo-Backend-CA-AplicationLayer.csproj" />
    <ProjectReference Include="..\ToDo-Backend-CA-EnterpriseLayer\ToDo-Backend-CA-EnterpriseLayer.csproj" />
    <ProjectReference Include="..\ToDo-Backend-CA-IntefaceAdapters-Presenters\ToDo-Backend-CA-IntefaceAdapters-Presenters.csproj" />
    <ProjectReference Include="..\ToDo-Backend-CA-InterfaceAdapters-Data\ToDo-Backend-CA-InterfaceAdapters-Data.csproj" />
    <ProjectReference Include="..\ToDo-Backend-InterfaceAdapters-Mappers\ToDo-Backend-InterfaceAdapters-Mappers.csproj" />
    <ProjectReference Include="..\ToDo-Backend-InterfaceAdapters-Models\ToDo-Backend-InterfaceAdapters-Models.csproj" />
  </ItemGroup>

</Project>
