name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          echo "🚀 Iniciando SonarQube Analysis..."
          
          # Navegar al directorio del backend
          cd ToDo-Backend

          # Iniciar el análisis de SonarQube
          ../.sonar/scanner/dotnet-sonarscanner begin /k:"JorgeAndres-GitHub_To-Do-Web" /o:"jorgeandres-github" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="${{ github.workspace }}/ToDo-Backend-CA-TestUnit/coverage.opencover.xml"

          # Restaurar dependencias y compilar
          dotnet restore
          dotnet build --no-restore ToDo-Backend.sln

          echo "✅ Build completado. Ejecutando pruebas unitarias con cobertura..."

          # Ejecutar pruebas unitarias con cobertura de código
          dotnet test ToDo-Backend-CA-TestUnit/ToDo-Backend-CA-TestUnit.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.xml

          echo "🔍 Verificando si el archivo coverage.opencover.xml se generó correctamente..."

          # Verificar si el archivo de cobertura existe
          if (Test-Path "ToDo-Backend-CA-TestUnit/coverage.opencover.xml") {
            echo "✅ Archivo coverage.opencover.xml encontrado. Continuando con el análisis..."
          } else {
            echo "❌ ERROR: No se encontró coverage.opencover.xml. Abortando análisis..."
            exit 1
          }

          # Finalizar análisis de SonarQube
          ../.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          
          echo "✅ Análisis de SonarQube completado correctamente. 🚀"
